export const allProjects = [
  {
    altText: "gradient maker homepage",
    appUrl: "/gradient-maker",
    codeUrl: "https://github.com/AwrenNuit/full-stack-software-developer-portfolio/tree/master/src/components/CustomGradient",
    descriptionLineOne: "Create a custom gradient",
    descriptionLineTwo: "with this tool",
    image: "images/screenshots/gradient-maker.png",
    oneButton: false,
    title: "Gradient Maker",
  },
  {
    altText: "gradient swatches art gallery",
    appUrl: "/swatches",
    codeUrl: "https://github.com/AwrenNuit/full-stack-software-developer-portfolio/tree/master/src/components/Swatches",
    descriptionLineOne: "A collection of some of",
    descriptionLineTwo: "my favorite gradients",
    image: "images/screenshots/swatches.png",
    oneButton: false,
    title: "Gradient Swatches",
  },
  {
    altText: "household hub homepage",
    codeUrl: "https://github.com/AwrenNuit/home-shopping-list",
    descriptionLineOne: "A place to consolidate shopping lists,",
    descriptionLineTwo: "chores, recipes, etc.",
    image: "images/screenshots/household-hub.png",
    oneButton: true,
    title: "Household Hub",
  },
  {
    altText: "homebody app's homepage",
    codeUrl: "https://github.com/AwrenNuit/HTG-WorkoutApp-2020",
    descriptionLineOne: "Hack The Gap weekend virtual hackathon",
    descriptionLineTwo: "project conceived and built by a team of five",
    externalAppUrl: "https://htg2020-homebody.web.app/",
    image: "images/screenshots/homebody.png",
    oneButton: false,
    title: "Homebody",
  },
  {
    altText: "evening javascript homepage",
    codeUrl: "https://github.com/AwrenNuit/evening-javascript",
    descriptionLineOne: "Small, odd evening projects",
    descriptionLineTwo: "utilizing vanilla JavaScript",
    externalAppUrl: "https://evening-javascript.web.app/index.html",
    image: "images/screenshots/evening-js.png",
    oneButton: false,
    title: "Evening JavaScript",
  },
  {
    altText: "tarot ascii logo",
    codeUrl: "https://github.com/AwrenNuit/perl-tarot-reading",
    descriptionLineOne: "Perl script that initiates a",
    descriptionLineTwo: "command line fortune telling game",
    image: "images/screenshots/tarot.png",
    oneButton: true,
    title: "Tarot",
  },
  {
    altText: "set timer page",
    appUrl: "/timer",
    codeUrl: "https://github.com/AwrenNuit/countdown-timer",
    descriptionLineOne: "Constructed to gain a better",
    descriptionLineTwo: "understanding of time",
    image: "images/screenshots/timer.png",
    oneButton: false,
    title: "Countdown Timer",
  },
  {
    altText: "alumni tracker table",
    codeUrl: "https://github.com/AwrenNuit/alum-tracker",
    descriptionLineOne: "Basic solution to track which events Prime",
    descriptionLineTwo: "Digital Academy alumni are attending",
    image: "images/screenshots/tracker.png",
    oneButton: true,
    title: "Alumni Tracker",
  },
  {
    altText: "password generator main page",
    appUrl: "/password-generator",
    codeUrl: "https://github.com/AwrenNuit/unique-id-generator",
    descriptionLineOne: "An exercise in basic password",
    descriptionLineTwo: "and ID generation",
    image: "images/screenshots/password.png",
    oneButton: false,
    title: "Password Generator",
  },
  {
    altText: "pixel art main page",
    appUrl: "/abstract-art",
    codeUrl: "https://github.com/AwrenNuit/abstract-pixel-art",
    descriptionLineOne: "Fusing my love for both",
    descriptionLineTwo: "experimental art and technology",
    image: "images/screenshots/art.png",
    oneButton: false,
    title: "Abstract Pixel Art",
  },
];
