export const allProjects = [
  {
    altText: 'gradient maker homepage',
    appUrl: '/gradient-maker',
    codeUrl:
      'https://github.com/awrennuit/full-stack-software-developer-portfolio/blob/master/src/components/CustomGradient/CustomGradient.jsx',
    description: 'Create a custom gradient with this tool',
    image: 'images/screenshots/gradient-maker.webp',
    oneButton: false,
    title: 'Gradient Maker',
  },
  {
    altText: 'gradient swatches art gallery',
    appUrl: '/swatches',
    codeUrl:
      'https://github.com/awrennuit/full-stack-software-developer-portfolio/blob/master/src/components/Swatches.jsx',
    description: 'A collection of some of my favorite gradients',
    image: 'images/screenshots/swatches.webp',
    oneButton: false,
    title: 'Gradient Swatches',
  },
  {
    altText: 'household hub homepage',
    codeUrl: 'https://github.com/awrennuit/home-shopping-list',
    description: 'A place to consolidate shopping lists, chores, recipes, etc.',
    image: 'images/screenshots/household-hub.webp',
    oneButton: true,
    title: 'Household Hub',
  },
  {
    altText: 'homebody app’s homepage',
    codeUrl: 'https://github.com/awrennuit/HTG-WorkoutApp-2020',
    description:
      'Hack The Gap weekend virtual hackathon project conceived and built by a team of five',
    externalAppUrl: 'https://htg2020-homebody.web.app/',
    image: 'images/screenshots/homebody.webp',
    oneButton: false,
    title: 'Homebody',
  },
  {
    altText: 'evening javascript homepage',
    codeUrl: 'https://github.com/awrennuit/evening-javascript',
    description: 'Small, odd evening projects utilizing vanilla JavaScript',
    externalAppUrl: 'https://evening-javascript.web.app/index.html',
    image: 'images/screenshots/evening-js.webp',
    oneButton: false,
    title: 'Evening JavaScript',
  },
  {
    altText: 'tarot ascii logo',
    codeUrl: 'https://github.com/awrennuit/perl-tarot-reading',
    description:
      'Perl script that initiates a command line fortune telling game',
    image: 'images/screenshots/tarot.webp',
    oneButton: true,
    title: 'Tarot',
  },
  {
    altText: 'set timer page',
    appUrl: '/timer',
    codeUrl: 'https://github.com/awrennuit/countdown-timer',
    description: 'Constructed to gain a better understanding of time',
    image: 'images/screenshots/timer.webp',
    oneButton: false,
    title: 'Countdown Timer',
  },
  {
    altText: 'alumni tracker table',
    codeUrl: 'https://github.com/awrennuit/alum-tracker',
    description:
      'Basic solution to track which events Prime Digital Academy alumni are attending',
    image: 'images/screenshots/tracker.webp',
    oneButton: true,
    title: 'Alumni Tracker',
  },
  {
    altText: 'password generator main page',
    appUrl: '/password-generator',
    codeUrl: 'https://github.com/awrennuit/unique-id-generator',
    description: 'An exercise in basic password and ID generation',
    image: 'images/screenshots/password.webp',
    oneButton: false,
    title: 'Password Generator',
  },
  {
    altText: 'pixel art main page',
    appUrl: '/abstract-art',
    codeUrl: 'https://github.com/awrennuit/abstract-pixel-art',
    description: 'Fusing my love for both experimental art and technology',
    image: 'images/screenshots/art.webp',
    oneButton: false,
    title: 'Abstract Pixel Art',
  },
];
