export const bandcampAlbums = {
  'awren (atmospheric black metal)': [
    {
      albumId: '1205304009',
      label: 'decaying memories - 2022',
      link: 'https://cavebirdrecords.bandcamp.com/album/decaying-memories',
      linkLabel: 'decaying memories by awren',
    },
    {
      albumId: '3536867511',
      label: 'Dreams - 2016',
      link: 'https://cavebirdrecords.bandcamp.com/album/dreams',
      linkLabel: 'Dreams by awren',
    },
    {
      albumId: '1621410143',
      label: 'A Wren EP - 2009',
      link: 'https://cavebirdrecords.bandcamp.com/album/a-wren-ep',
      linkLabel: 'A Wren EP by awren',
    },
  ],
  'chrysanthemum (ambient guitar)': [
    {
      albumId: '1764876855',
      label: 'the softest feeling the quietest touch - 2023',
      link: 'https://cavebirdrecords.bandcamp.com/album/the-softest-feeling-the-quietest-touch',
      linkLabel: 'the softest feeling the quietest touch by chrysanthemum',
    },
    {
      albumId: '492363530',
      label: 'Thaw - 2019',
      link: 'https://cavebirdrecords.bandcamp.com/album/thaw',
      linkLabel: 'Thaw by chrysanthemum',
    },
    {
      albumId: '3581577905',
      label: 'Journeying From Death to Rebirth - 2015',
      link: 'https://cavebirdrecords.bandcamp.com/album/journeying-from-death-to-rebirth',
      linkLabel: 'Journeying From Death to Rebirth by chrysanthemum',
    },
    {
      albumId: '2028220265',
      label: 'chrysanthemum - 2013',
      link: 'https://cavebirdrecords.bandcamp.com/album/chrysanthemum',
      linkLabel: 'chrysanthemum by chrysanthemum',
    },
    {
      albumId: '3285176979',
      label: 'A Taste of Things to Come - 2013',
      link: 'https://cavebirdrecords.bandcamp.com/album/a-taste-of-things-to-come',
      linkLabel: 'A Taste of Things to Come by chrysanthemum',
    },
  ],
  'Gloomthread (funeral doom)': [
    {
      albumId: '993920283',
      label: 'Shadow Walk - 2018',
      link: 'https://cavebirdrecords.bandcamp.com/album/shadow-walk',
      linkLabel: 'Shadow Walk by Gloomthread',
    },
    {
      albumId: '598059969',
      label: 'Winter Kings - 2016',
      link: 'https://cavebirdrecords.bandcamp.com/album/winter-kings',
      linkLabel: 'Winter Kings by Gloomthread',
    },
  ],
  'Wooden Vessels (dungeon synth)': [
    {
      albumId: '1908782603',
      label: 'That Which is in Death Shall Grant Life Without End - 2024',
      link: 'https://cavebirdrecords.bandcamp.com/album/that-which-is-in-death-shall-grant-life-without-end',
      linkLabel:
        'That Which is in Death Shall Grant Life Without End by Wooden Vessels',
    },
    {
      albumId: '1634272242',
      label: 'What Lies in Wait - 2024',
      link: 'https://cavebirdrecords.bandcamp.com/album/what-lies-in-wait',
      linkLabel: 'What Lies in Wait by Wooden Vessels',
    },
    {
      albumId: '2752846756',
      label: 'Live from the Three Horses Inn - 2024',
      link: 'https://cavebirdrecords.bandcamp.com/album/live-from-the-three-horses-inn',
      linkLabel: 'Live from the Three Horses Inn by Wooden Vessels',
    },
    {
      albumId: '2166652131',
      label: 'Lullabies of a Bygone Age - 2024',
      link: 'https://cavebirdrecords.bandcamp.com/album/lullabies-of-a-bygone-age',
      linkLabel: 'Lullabies of a Bygone Age by Wooden Vessels',
    },
    {
      albumId: '578722557',
      label: 'Meadowtrek Woods: Life and Ecology - 2023',
      link: 'https://cavebirdrecords.bandcamp.com/album/meadowtrek-woods-life-and-ecology',
      linkLabel: 'Meadowtrek Woods: Life and Ecology by Wooden Vessels',
    },
    {
      albumId: '3277503005',
      label: 'The Beloved Emperor - 2023',
      link: 'https://cavebirdrecords.bandcamp.com/album/the-beloved-emperor',
      linkLabel: 'The Beloved Emperor by Wooden Vessels',
    },
    {
      albumId: '3395428764',
      label: 'To Slumber Beneath a Blanket of White  - 2023',
      link: 'https://cavebirdrecords.bandcamp.com/album/to-slumber-beneath-a-blanket-of-white',
      linkLabel: 'To Slumber Beneath a Blanket of White by Wooden Vessels',
    },
    {
      albumId: '3945216184',
      label: 'Abandoned Crypt of the Blasphemous Lord - 2022',
      link: 'https://cavebirdrecords.bandcamp.com/album/abandoned-crypt-of-the-blasphemous-lord',
      linkLabel: 'Abandoned Crypt of the Blasphemous Lord by Wooden Vessels',
    },
  ],
};

export const dungeonVaultAlbums = {
  'an_old_witch’s_hat': {
    albumId: '4081667564',
    artist: 'An Old Witch’s Hat',
    label: 'A Pact of Warlock Tears and Lycanthropic Divinity - 2023',
    link: 'https://serpentsswordrecords.bandcamp.com/album/a-pact-of-warlock-tears-and-lycanthropic-divinity',
    linkLabel:
      'A Pact of Warlock Tears and Lycanthropic Divinity by An Old Witch’s Hat',
  },
  ancient_boreal_forest: {
    albumId: '4027050997',
    artist: 'Ancient Boreal Forest',
    label: 'Cold Ethereal Winter - 2017',
    link: 'https://ancientborealforest.bandcamp.com/album/cold-ethereal-winter',
    linkLabel: 'Cold Ethereal Winter by Ancient Boreal Forest',
  },
  ancient_invocations: {
    albumId: '4261526893',
    artist: 'Ancient Invocations',
    label: 'Solitude in a Starry Sky - 2023',
    link: 'https://ancientinvocations.bandcamp.com/album/solitude-in-a-starry-sky',
    linkLabel: 'Solitude in a Starry Sky by Ancient Invocations',
  },
  anser: {
    albumId: '3363363148',
    artist: 'Anser',
    label: 'Apostate - 2023',
    link: 'https://ansersynth.bandcamp.com/album/apostate',
    linkLabel: 'Apostate by Anser',
  },
  archmast: {
    albumId: '3800077581',
    artist: 'Archmast',
    label: 'As the Wind Carries Us - 2023',
    link: 'https://archmast.bandcamp.com/album/as-the-wind-carries-us',
    linkLabel: 'As the Wind Carries Us by Archmast',
  },
  arvondrakh: {
    albumId: '110306453',
    artist: 'Arvondrakh',
    label: 'Arvondrakh I - 2023',
    link: 'https://arvondrakh.bandcamp.com/album/arvondrakh-i',
    linkLabel: 'Arvondrakh I by Arvondrakh',
  },
  atlantean_sword: {
    albumId: '3391845468',
    artist: 'Atlantean Sword',
    label: 'Cimmerian Solitude - 2023',
    link: 'https://atlanteansword.bandcamp.com/album/atlantean-sword-cimmerian-solitude-demo-mmxxiii',
    linkLabel:
      'Atlantean Sword - Cimmerian Solitude (Demo) MMXXIII by Atlantean Sword',
  },
  atrium_of_time: {
    albumId: '421868206',
    artist: 'Atrium of Time',
    label: 'Atrium of Time - 2023',
    link: 'https://atriumoftime.bandcamp.com/album/atrium-of-time',
    linkLabel: 'Atrium of Time by Atrium of Time',
  },
  bakt: {
    albumId: '1901491086',
    artist: 'Bakt',
    label: 'Cores de Arquea - 2023',
    link: 'https://bakt.bandcamp.com/album/cores-de-arquea',
    linkLabel: 'Cores de Arquea by Bakt',
  },
  bartizan_chill: {
    albumId: '4252540934',
    artist: 'Bartizan Chill',
    label: 'Live at Sailors Arms - 2024',
    link: 'https://bartizanchill.bandcamp.com/album/live-at-sailors-arms',
    linkLabel: 'Live At Sailors Arms by Bartizan Chill',
  },
  chanterelle: {
    albumId: '3220478371',
    artist: 'Chanterelle',
    label: 'Tales from the Forest Floor - 2021',
    link: 'https://chanterelle.bandcamp.com/album/tales-from-the-forest-floor',
    linkLabel: 'Tales from the Forest Floor by Chanterelle',
  },
  deionarra: {
    albumId: '3494547514',
    artist: 'Deionarra',
    label: 'The Suicide God - 2023',
    link: 'https://deionarra.bandcamp.com/album/the-suicide-god',
    linkLabel: 'The Suicide God by Deionarra',
  },
  depressive_silence: {
    albumId: '2099193775',
    artist: 'Depressive Silence',
    label: 'Depressive Silence II - 1996',
    link: 'https://a-spell-enraged.bandcamp.com/album/mourning-remastered',
    linkLabel: 'Mourning (remastered) by DEPRESSIVE SILENCE',
  },
  descort: {
    albumId: '160826441',
    artist: 'Descort',
    label: 'Ysopet 1er - 2021',
    link: 'https://descort.bandcamp.com/album/ysopet-1er',
    linkLabel: 'Ysopet 1er by Descort',
  },
  desolazione_rurale: {
    albumId: '2164699977',
    artist: 'Desolazione Rurale',
    label: 'Verso l’alba - 2023',
    link: 'https://desolazionerurale.bandcamp.com/album/verso-lalba',
    linkLabel: 'Verso l’alba by Desolazione Rurale',
  },
  dim: {
    albumId: '2754431056',
    artist: 'DIM',
    label: 'Compendium III - 2020',
    link: 'https://iamdim.bandcamp.com/album/compendium-iii',
    linkLabel: 'Compendium III by DIM',
  },
  diplodocus: {
    albumId: '1154173385',
    artist: 'Diplodocus',
    label: 'Slow And Heavy - 2019',
    link: 'https://diplodocus.bandcamp.com/album/slow-and-heavy',
    linkLabel: 'Slow And Heavy by Diplodocus',
  },
  dusklight: {
    albumId: '1747122653',
    artist: 'Dusklight',
    label: 'Key XIV - 2023',
    link: 'https://windkeytapes.bandcamp.com/album/key-xiv-enchantment-serenity',
    linkLabel: 'Key XIV: Enchantment &amp; Serenity by Dusklight',
  },
  dust_seeker: {
    albumId: '1950139173',
    artist: 'Dust Seeker',
    label: 'The Golden Compass - 2019',
    link: 'https://dustseeker.bandcamp.com/album/the-golden-compass',
    linkLabel: 'The Golden Compass by Dust Seeker',
  },
  ephemerus: {
    albumId: '2781382904',
    artist: 'Ephemerus',
    label: 'Ephemera II - 2022',
    link: 'https://disquieting.bandcamp.com/album/ephemera-ii',
    linkLabel: 'Ephemera II by Ephemerus',
  },
  erang: {
    albumId: '3205634662',
    artist: 'Erang',
    label: 'Another World Another Time - 2013',
    link: 'https://erang.bandcamp.com/album/another-world-another-time',
    linkLabel: 'Another World Another Time by Erang',
  },
  erythrite_throne: {
    albumId: '1905769229',
    artist: 'Erythrite Throne',
    label: 'Through Caliginous Tombs Where Pale Horses Dream - 2022',
    link: 'https://serpentsswordrecords.bandcamp.com/album/through-caliginous-tombs-where-pale-horses-dream',
    linkLabel:
      'Through Caliginous Tombs Where Pale Horses Dream by Erythrite Throne',
  },
  estoc: {
    albumId: '2226416085',
    artist: 'ESTOC',
    label: 'Chapter I - 2019',
    link: 'https://estoc1.bandcamp.com/album/chapter-i',
    linkLabel: 'Chapter I by ESTOC',
  },
  fenmoss: {
    albumId: '3531789836',
    artist: 'Fenmoss',
    label: 'Reawakened Wisdom - 2024',
    link: 'https://barony-of-fenmoss.bandcamp.com/album/reawakened-wisdom',
    linkLabel: 'Reawakened Wisdom by Fenmoss',
  },
  fief: {
    albumId: '3763192730',
    artist: 'Fief',
    label: 'II - 2016',
    link: 'https://fief.bandcamp.com/album/ii',
    linkLabel: 'II by Fief',
  },
  fogweaver: {
    albumId: '4181215458',
    artist: 'Fogweaver',
    label: 'Vedurnan - 2020',
    link: 'https://thefogweaver.bandcamp.com/album/vedurnan',
    linkLabel: 'Vedurnan by Fogweaver',
  },
  forgotten_phantasm: {
    albumId: '2387182410',
    artist: 'Forgotten Phantasm',
    label: '♜♜♜♜♜♜♜ - 2024',
    link: 'https://forgottenphantasm.bandcamp.com/album/-',
    linkLabel: '♜♜♜♜♜♜♜ by Forgotten Phantasm',
  },
  forlorn: {
    albumId: '3237544710',
    artist: 'Forlorn',
    label: 'Forlorn - 2024',
    link: 'https://forlorn-ds.bandcamp.com/album/forlorn',
    linkLabel: 'Forlorn by Forlorn',
  },
  frostgard: {
    albumId: '2721127097',
    artist: 'Frostgard',
    label: 'Valaquenta I - 2021',
    link: 'https://frostgard-dungeonsynth.bandcamp.com/album/valaquenta-i',
    linkLabel: 'Valaquenta I by Frostgard',
  },
  gelure: {
    albumId: '255396186',
    artist: 'Gelure',
    label: 'The Candlelight Tomes - 2021',
    link: 'https://gelure.bandcamp.com/album/the-candlelight-tomes',
    linkLabel: 'The Candlelight Tomes by Gelure',
  },
  gorgons_alter: {
    albumId: '3261724646',
    artist: 'Gorgons Alter',
    label: 'Arcane and Abel - 2024',
    link: 'https://gorgonsalter.bandcamp.com/album/arcane-and-abel',
    linkLabel: 'Arcane and Abel by Gorgons Alter',
  },
  herdade: {
    albumId: '1080988963',
    artist: 'Herdade',
    label: 'Livro Primeiro - 2022',
    link: 'https://herdade.bandcamp.com/album/livro-primeiro',
    linkLabel: 'Livro Primeiro by Herdade',
  },
  hermit_knight: {
    albumId: '318911255',
    artist: 'Hermit Knight',
    label: 'adventures in depersonalization - 2023',
    link: 'https://hermitknight.bandcamp.com/album/adventures-in-depersonalization',
    linkLabel: 'adventures in depersonalization by Hermit Knight',
  },
  hibernal_harvest: {
    albumId: '4152867053',
    artist: 'Hibernal Harvest',
    label: 'Dreamspire - 2023',
    link: 'https://hibernalharvest.bandcamp.com/album/dreamspire',
    linkLabel: 'Dreamspire by Hibernal Harvest',
  },
  hircine: {
    albumId: '1214115397',
    artist: 'Hircine',
    label: 'Old Kings Fall - 2022',
    link: 'https://songsofhircine.bandcamp.com/album/old-kings-fall',
    linkLabel: 'Old Kings Fall by Hircine',
  },
  hjartans: {
    albumId: '4114641268',
    artist: 'Hjartans',
    label: 'Open your heart to the Night - 2024',
    link: 'https://hjartans.bandcamp.com/album/open-your-heart-to-the-night',
    linkLabel: 'Open your heart to the Night by Hjartans',
  },
  hyperborean_might: {
    albumId: '3522688156',
    artist: 'Hyperborean Might',
    label: 'Within The Age Of Savagery - 2023',
    link: 'https://ithildintapeproduction.bandcamp.com/album/within-the-age-of-savagery',
    linkLabel: 'Within The Age Of Savagery by Hyperborean Might',
  },
  koryos: {
    albumId: '416583136',
    artist: 'Koryos',
    label: 'Realm of the White Tiger - 2023',
    link: 'https://ageofkoryos.bandcamp.com/album/realm-of-the-white-tiger',
    linkLabel: 'Realm of the White Tiger by Kóryos',
  },
  kyvon: {
    albumId: '2426135048',
    artist: 'Kyvon',
    label: 'Courtier - 2023',
    link: 'https://kyvon.bandcamp.com/album/courtier',
    linkLabel: 'Courtier by Kyvon',
  },
  lone_sentinel: {
    albumId: '1976600274',
    artist: 'Lone Sentinel',
    label: 'Adventure Calls Thy Name - 2023',
    link: 'https://hammerandflailrecordings.bandcamp.com/album/adventure-calls-thy-name',
    linkLabel: 'Adventure Calls Thy Name by Lone Sentinel',
  },
  the_loreseeker: {
    albumId: '2815154567',
    artist: 'The Loreseeker',
    label: 'Where the Moonlight Herb Grows - 2020',
    link: 'https://theloreseeker.bandcamp.com/album/where-the-moonlight-herb-grows',
    linkLabel: 'Where the Moonlight Herb Grows by The Loreseeker',
  },
  losgann: {
    albumId: '3442329119',
    artist: 'Losgann',
    label: 'Lakespell - 2021',
    link: 'https://losgann.bandcamp.com/album/lakespell',
    linkLabel: 'Lakespell by Losgann',
  },
  lost_woods: {
    albumId: '4107200645',
    artist: 'Lost Woods',
    label: 'Abandoned - 2020',
    link: 'https://thelostwoods.bandcamp.com/album/abandoned',
    linkLabel: 'Abandoned by Lost Woods',
  },
  lugubrious_chant: {
    albumId: '167600791',
    artist: 'Lugubrious Chant',
    label: 'Macabre Aurae - 2020',
    link: 'https://lugubriouschant.bandcamp.com/album/macabre-aurae',
    linkLabel: 'Macabre Aurae by Lugubrious Chant',
  },
  lunar_womb: {
    albumId: '1930718337',
    artist: 'Lunar Womb',
    label: 'The Sleeping Green - 1999',
    link: 'https://worldoftrollhorn.bandcamp.com/album/the-sleeping-green',
    linkLabel: 'The Sleeping Green by Lunar Womb',
  },
  mark_ellery_griffiths: {
    albumId: '2816429900',
    artist: 'Mark Ellery Griffiths',
    label: 'K2 - 1987',
    link: 'https://markgriffiths.bandcamp.com/album/k2-1987',
    linkLabel: 'K2 by Mark Ellery Griffiths',
  },
  maximum_mana: {
    albumId: '3847176149',
    artist: 'Maximum Mana',
    label: 'Live at the Black Bridge - 2024',
    link: 'https://maximummana.bandcamp.com/album/live-at-the-black-bridge',
    linkLabel: 'Live at the Black Bridge by Maximum Mana',
  },
  moonkeeper: {
    albumId: '3865733876',
    artist: 'MoonKeeper',
    label: 'The Keeper’s Odyssey - 2023',
    link: 'https://moonkeeper.bandcamp.com/album/the-keepers-odyssey',
    linkLabel: 'The Keeper’s Odyssey by MoonKeeper',
  },
  moonkissed_spires: {
    albumId: '1454872167',
    artist: 'Moonkissed Spires',
    label: 'Hymns of the Battlefield - 2024',
    link: 'https://moonkissedspires.bandcamp.com/album/hymns-of-the-battlefield',
    linkLabel: 'Hymns of the Battlefield by Moonkissed Spires',
  },
  mordiford_dragon: {
    albumId: '136601526',
    artist: 'Mordiford Dragon',
    label: 'The Tale of the Mordiford Dragon Part I - 2022',
    link: 'https://mordiforddragon.bandcamp.com/album/the-tale-of-the-mordiford-dragon-part-i',
    linkLabel: 'The Tale of the Mordiford Dragon Part I by Mordiford Dragon',
  },
  morke_og_lys: {
    albumId: '329813403',
    artist: 'Morke Og Lys',
    label: 'Lethal Sphere - 2022',
    link: 'https://morkeoglys.bandcamp.com/album/lethal-sphere',
    linkLabel: 'Lethal Sphere by 𝔐ø𝔯𝔨𝔢 𝔒𝔤 𝔏𝔶𝔰',
  },
  morrowsworn: {
    albumId: '1900121955',
    artist: 'Morrowsworn',
    label: 'Where Crowns Are Forged Of Stars - 2021',
    link: 'https://sijmusicart.bandcamp.com/album/where-crowns-are-forged-of-stars',
    linkLabel: 'Where Crowns Are Forged Of Stars by Morrowsworn',
  },
  nan_morlith: {
    albumId: '2989012696',
    artist: 'Nan Morlith',
    label: 'Âdhûn & Fangorn - 2020',
    link: 'https://nanmorlith.bandcamp.com/album/dh-n-fangorn',
    linkLabel: 'Âdhûn & Fangorn by Nan Morlith',
  },
  nest: {
    albumId: '2433808251',
    artist: 'Nest',
    label: 'Hidden Stream - 2001',
    link: 'ttps://nestfin.bandcamp.com/album/hidden-stream',
    linkLabel: 'Hidden Stream by Nest',
  },
  porcelain_sword: {
    albumId: '2983422098',
    artist: 'Porcelain Sword',
    label: 'Porcelain Sword - 2023',
    link: 'https://porcelainsword.bandcamp.com/album/porcelain-sword',
    linkLabel: 'Porcelain Sword by Porcelain Sword',
  },
  pumpkin_golem: {
    albumId: '1851916512',
    artist: 'Pumpkin Golem',
    label: 'Rise of the Pumpkin Golem - 2024',
    link: 'https://blindsorceress.bandcamp.com/album/rise-of-the-pumpkin-golem-ep',
    linkLabel: 'Rise of the Pumpkin Golem by Pumpkin Golem',
  },
  refusa: {
    albumId: '3025787786',
    artist: 'Refusa',
    label: 'In Muck and Mire | Turned to Sludge - 2024',
    link: 'https://refusa.bandcamp.com/album/in-muck-and-mire-turned-to-sludge',
    linkLabel: 'In Muck and Mire | Turned to Sludge by Refusa',
  },
  rog: {
    albumId: '1783752788',
    artist: 'Rog',
    label: 'Brave sir Robin - 2018',
    link: 'https://rogofficial.bandcamp.com/album/brave-sir-robin',
    linkLabel: 'Brave sir Robin by Rog',
  },
  secret_stairways: {
    albumId: '3819909238',
    artist: 'Secret Stairways',
    label: 'Enchantment of the Ring - 1997',
    link: 'https://secretstairways.bandcamp.com/album/enchantment-of-the-ring',
    linkLabel: 'Enchantment of the Ring by Secret Stairways',
  },
  sequestered_keep: {
    albumId: '2116089096',
    artist: 'Sequestered Keep',
    label: 'The Oldest Realm - 2016',
    link: 'https://sequesteredkeep.bandcamp.com/album/the-oldest-realm',
    linkLabel: 'The Oldest Realm by Sequestered Keep',
  },
  silent_garden: {
    albumId: '3210086173',
    artist: 'Silent Garden',
    label: 'Demo II - 2022',
    link: 'https://silentgardenmusic.bandcamp.com/album/demo-ii',
    linkLabel: 'Demo II by Silent Garden',
  },
  skhemty: {
    albumId: '2525414357',
    artist: 'Skhemty',
    label: 'Sunrise on the Old Kingdom - 2022',
    link: 'https://skhemty.bandcamp.com/album/sunrise-on-the-old-kingdom',
    linkLabel: 'Sunrise on the Old Kingdom by Skhemty',
  },
  sombre_arcane: {
    albumId: '1137168445',
    artist: 'Sombre Arcane',
    label: 'Realmsong - 2021',
    link: 'https://sombrearcane.bandcamp.com/album/realmson',
    linkLabel: 'Realmsong by Sombre Arcane',
  },
  sophia: {
    albumId: '309704240',
    artist: 'Sophia',
    label: 'As We Weep at the Altar of Mourning - 2020',
    link: 'https://serpentsswordrecords.bandcamp.com/album/as-we-weep-at-the-altar-of-mourning',
    linkLabel: 'As We Weep at the Altar of Mourning by Sophia',
  },
  sourcerior: {
    albumId: '3365241793',
    artist: 'Sourcerior',
    label: 'Messère - 2022',
    link: 'https://sourcerior.bandcamp.com/album/mess-re',
    linkLabel: 'Messère by Sourcerior',
  },
  spectral_austräa: {
    albumId: '591195171',
    artist: 'Spectral Austräa',
    label: 'Solemn Spring - 2024',
    link: 'https://spectralaustraa.bandcamp.com/album/solemn-spring',
    linkLabel: 'Solemn Spring by Spectral Austräa',
  },
  spellbound_mire: {
    albumId: '2484794722',
    artist: 'Spellbound Mire',
    label: 'Spellbound Mire - 2022',
    link: 'https://spellboundmire.bandcamp.com/album/spellbound-mire',
    linkLabel: 'Spellbound Mire by Spellbound Mire',
  },
  spife: {
    albumId: '3139651231',
    artist: 'Spife',
    label: 'The Fulfillment of The ’Scapen - 2023',
    link: 'https://spife-dot-mp4.bandcamp.com/album/the-fulfillment-of-the-scapen',
    linkLabel: 'The Fulfillment of The ’Scapen by Spife',
  },
  sylfvr: {
    albumId: '3286080536',
    artist: 'Sylfvr',
    label: 'A Nice Evening Stroll - 2024',
    link: 'https://sylfvr.bandcamp.com/album/a-nice-evening-stroll',
    linkLabel: 'A Nice Evening Stroll by Sylfvr',
  },
  sylvan_echoes: {
    albumId: '708562239',
    artist: 'Sylvan Echoes',
    label: 'I - 2021',
    link: 'https://sylvanechoes.bandcamp.com/album/i',
    linkLabel: 'I by Sylvan Echoes',
  },
  tales_under_the_oak: {
    albumId: '1739046790',
    artist: 'Tales Under The Oak',
    label: 'The Toad Alchemy - 2023',
    link: 'https://talesundertheoak.bandcamp.com/album/the-toad-alchemy',
    linkLabel: 'The Toad Alchemy by Tales Under The Oak',
  },
  that_demon_the_sun: {
    albumId: '4250056751',
    artist: 'That Demon The Sun',
    label: 'Ghosted - 2023',
    link: 'https://hadeanhollerrecordings.bandcamp.com/album/ghosted',
    linkLabel: 'Ghosted by That Demon the Sun',
  },
  tree_gardener: {
    albumId: '1645476470',
    artist: 'Tree Gardener',
    label: 'Midwinter Memories - 2023',
    link: 'https://treegardener.bandcamp.com/album/midwinter-memories',
    linkLabel: 'Midwinter Memories by Tree Gardener',
  },
  ugrino: {
    albumId: '3898342440',
    artist: 'Ugrino',
    label: 'Miracle - 2023',
    link: 'https://ugrino.bandcamp.com/album/miracle',
    linkLabel: 'Miracle by Ugrino',
  },
  ulk: {
    albumId: '1014444236',
    artist: 'ulk',
    label: 'Restoration Magic - 2022',
    link: 'https://ulkmusic.bandcamp.com/album/restoration-magic',
    linkLabel: 'Restoration Magic by ulk',
  },
  under_the_frost_moon: {
    albumId: '2650200803',
    artist: 'Unsheathed Glory',
    label: 'The Forest of Forgotten Dreams - 2024',
    link: 'https://underthefrostmoon.bandcamp.com/album/the-forest-of-forgotten-dreams',
    linkLabel: 'The Forest of Forgotten Dreams by Under the Frost Moon',
  },
  unsheathed_glory: {
    albumId: '2087741473',
    artist: 'Unsheathed Glory',
    label: 'Fables from Featherwood Forest - 2023',
    link: 'https://unsheathedglory.bandcamp.com/album/fables-from-featherwood-forest',
    linkLabel: 'Fables from Featherwood Forest by Unsheathed Glory',
  },
  ur_pale: {
    albumId: '963888117',
    artist: 'Ur Pale',
    label: 'Sea Synth Ensemble - 2017',
    link: 'https://urpalemperor.bandcamp.com/album/sea-synth-ensemble',
    linkLabel: 'Sea Synth Ensemble by Ur Pale',
  },
  vale_minstrel: {
    albumId: '2024930507',
    artist: 'Vale Minstrel',
    label: 'Warden Of The Vale - 2020',
    link: 'https://valeminstrel.bandcamp.com/album/warden-of-the-vale',
    linkLabel: 'Warden Of The Vale by Vale Minstrel',
  },
  vanhellig: {
    albumId: '3518011199',
    artist: 'Vanhellig',
    label: 'The Ghost in the Spire - 2021',
    link: 'https://vanhellig.bandcamp.com/album/the-ghost-in-the-spire',
    linkLabel: 'The Ghost in the Spire by Vanhellig',
  },
  vanishing_amulet: {
    albumId: '3307847872',
    artist: 'Vanishing Amulet',
    label: 'Nocturnal Heritage - 2022',
    link: 'https://vanishingamulet.bandcamp.com/album/nocturnal-heritage',
    linkLabel: 'Nocturnal Heritage by Vanishing Amulet',
  },
  vermin_halls: {
    albumId: '3472821423',
    artist: 'Vermin Halls',
    label: 'Mourningwraith - 2022',
    link: 'https://pestilent-one.bandcamp.com/album/mourningwraith',
    linkLabel: 'Mourningwraith by Vermin Halls',
  },
  vetraheimr: {
    albumId: '1089464393',
    artist: 'Vetraheimr',
    label: 'The Renegade - 2019',
    link: 'https://vetraheimr.bandcamp.com/album/the-renegade',
    linkLabel: 'The Renegade by Vetraheimr',
  },
  villein: {
    albumId: '413853285',
    artist: 'Villein',
    label: 'Kreis - 2020',
    link: 'https://thevillein.bandcamp.com/album/kreis',
    linkLabel: 'Kreis by Villein',
  },
  vindkaldr: {
    albumId: '3116319128',
    artist: 'Vindkaldr',
    label: 'Enchantments Of Old Lore - 2015',
    link: 'https://vindkaldr.bandcamp.com/album/enchantments-of-old-lore',
    linkLabel: 'Enchantments Of Old Lore by Vindkaldr',
  },
  windspell: {
    albumId: '4223476907',
    artist: 'Windspell',
    label: 'Wilderness Sanctuary - 2023',
    link: 'https://windspell-realm.bandcamp.com/album/wilderness-sanctuary',
    linkLabel: 'Wilderness Sanctuary by Windspell',
  },
  wingthalion: {
    albumId: '2294069635',
    artist: 'Wingthalion',
    label: 'To Find Solace in the Stillness - 2020',
    link: 'https://wingthalion.bandcamp.com/album/to-find-solace-in-the-stillness',
    linkLabel: 'To Find Solace in the Stillness by Wingthalion',
  },
  wooden_lungs: {
    albumId: '3680094735',
    artist: 'Wooden Lungs',
    label: 'Quiet Places - 2023',
    link: 'https://woodenlungs.bandcamp.com/album/quiet-places',
    linkLabel: 'Quiet Places by Wooden Lungs',
  },
};
