export const bandcampAlbums = {
  'awren (atmospheric black metal)': [
    {
      albumId: '1205304009',
      label: 'decaying memories - 2022',
      link: 'https://cavebirdrecords.bandcamp.com/album/decaying-memories',
      linkLabel: 'decaying memories by awren',
    },
    {
      albumId: '3536867511',
      label: 'Dreams - 2016',
      link: 'https://cavebirdrecords.bandcamp.com/album/dreams',
      linkLabel: 'Dreams by awren',
    },
    {
      albumId: '1621410143',
      label: 'A Wren EP - 2009',
      link: 'https://cavebirdrecords.bandcamp.com/album/a-wren-ep',
      linkLabel: 'A Wren EP by awren',
    },
  ],
  'chrysanthemum (ambient guitar)': [
    {
      albumId: '1135978160',
      label: 'a stillness outside the window - 2025',
      link: 'https://cavebirdrecords.bandcamp.com/album/a-stillness-outside-the-window',
      linkLabel: 'a stillness outside the window by chrysanthemum',
    },
    {
      albumId: '1764876855',
      label: 'the softest feeling the quietest touch - 2023',
      link: 'https://cavebirdrecords.bandcamp.com/album/the-softest-feeling-the-quietest-touch',
      linkLabel: 'the softest feeling the quietest touch by chrysanthemum',
    },
    {
      albumId: '492363530',
      label: 'Thaw - 2019',
      link: 'https://cavebirdrecords.bandcamp.com/album/thaw',
      linkLabel: 'Thaw by chrysanthemum',
    },
    {
      albumId: '3581577905',
      label: 'Journeying From Death to Rebirth - 2015',
      link: 'https://cavebirdrecords.bandcamp.com/album/journeying-from-death-to-rebirth',
      linkLabel: 'Journeying From Death to Rebirth by chrysanthemum',
    },
    {
      albumId: '2028220265',
      label: 'chrysanthemum - 2013',
      link: 'https://cavebirdrecords.bandcamp.com/album/chrysanthemum',
      linkLabel: 'chrysanthemum by chrysanthemum',
    },
    {
      albumId: '3285176979',
      label: 'A Taste of Things to Come - 2013',
      link: 'https://cavebirdrecords.bandcamp.com/album/a-taste-of-things-to-come',
      linkLabel: 'A Taste of Things to Come by chrysanthemum',
    },
  ],
  'Gloomthread (funeral doom)': [
    {
      albumId: '993920283',
      label: 'Shadow Walk - 2018',
      link: 'https://cavebirdrecords.bandcamp.com/album/shadow-walk',
      linkLabel: 'Shadow Walk by Gloomthread',
    },
    {
      albumId: '598059969',
      label: 'Winter Kings - 2016',
      link: 'https://cavebirdrecords.bandcamp.com/album/winter-kings',
      linkLabel: 'Winter Kings by Gloomthread',
    },
  ],
  'Wooden Vessels (dungeon synth)': [
    {
      albumId: '3738689127',
      label: 'Live at Grace Center - 2026',
      link: 'https://cavebirdrecords.bandcamp.com/album/live-at-grace-center',
      linkLabel: 'Live at Grace Center by Wooden Vessels',
    },
    {
      albumId: '1023187973',
      label: 'The Very Best of Wooden Vessels 2021-2025 - 2025',
      link: 'https://cavebirdrecords.bandcamp.com/album/the-very-best-of-wooden-vessels-2021-2025',
      linkLabel: 'The Very Best of Wooden Vessels 2021-2025 by Wooden Vessels',
    },
    {
      albumId: '3832920755',
      label: 'Dagorby Pomme’s Magickal Emporium - 2025',
      link: 'https://cavebirdrecords.bandcamp.com/album/dagorby-pommes-magickal-emporium',
      linkLabel: 'Dagorby Pomme’s Magickal Emporium by Wooden Vessels',
    },
    {
      albumId: '487786529',
      label: 'Virtual Dungeon Crawl Set - 2025',
      link: 'https://cavebirdrecords.bandcamp.com/album/virtual-dungeon-crawl-set',
      linkLabel: 'Virtual Dungeon Crawl Set by Wooden Vessels',
    },
    {
      albumId: '3376078526',
      label: 'Aveline’s Synth1 Dungeon Synth Bank (NOT AN ALBUM) - 2025',
      link: 'https://cavebirdrecords.bandcamp.com/album/avelines-synth1-dungeon-synth-bank',
      linkLabel: 'Aveline’s Synth1 Dungeon Synth Bank by Aveline Baudelaire',
    },
    {
      albumId: '870420289',
      label: 'Rise of the Woodland Empire - 2025',
      link: 'https://cavebirdrecords.bandcamp.com/album/rise-of-the-woodland-empire',
      linkLabel: 'Rise of the Woodland Empire by Wooden Vessels',
    },
    {
      albumId: '426352869',
      label: 'A Sunless Winter (split with Hibernal Harvest) - 2025',
      link: 'https://cavebirdrecords.bandcamp.com/album/a-sunless-winter-split-with-hibernal-harvest',
      linkLabel:
        'A Sunless Winter (split with Hibernal Harvest) by Wooden Vessels / Hiberal Harvest',
    },
    {
      albumId: '2767721795',
      label: 'With Both Feet Upon the Aether - 2025',
      link: 'https://cavebirdrecords.bandcamp.com/album/with-both-feet-upon-the-aether',
      linkLabel: 'With Both Feet Upon the Aether by Wooden Vessels',
    },
    {
      albumId: '3190851946',
      label: 'Paxtonirae, Fleeting Embodiment of Contrition - 2025',
      link: 'https://cavebirdrecords.bandcamp.com/album/paxtonirae-fleeting-embodiment-of-contrition',
      linkLabel:
        'Paxtonirae, Fleeting Embodiment of Contrition by Wooden Vessels',
    },
    {
      albumId: '1908782603',
      label: 'That Which is in Death Shall Grant Life Without End - 2024',
      link: 'https://cavebirdrecords.bandcamp.com/album/that-which-is-in-death-shall-grant-life-without-end',
      linkLabel:
        'That Which is in Death Shall Grant Life Without End by Wooden Vessels',
    },
    {
      albumId: '1634272242',
      label: 'What Lies in Wait - 2024',
      link: 'https://cavebirdrecords.bandcamp.com/album/what-lies-in-wait',
      linkLabel: 'What Lies in Wait by Wooden Vessels',
    },
    {
      albumId: '2752846756',
      label: 'Live from the Three Horses Inn - 2024',
      link: 'https://cavebirdrecords.bandcamp.com/album/live-from-the-three-horses-inn',
      linkLabel: 'Live from the Three Horses Inn by Wooden Vessels',
    },
    {
      albumId: '2166652131',
      label: 'Lullabies of a Bygone Age - 2024',
      link: 'https://cavebirdrecords.bandcamp.com/album/lullabies-of-a-bygone-age',
      linkLabel: 'Lullabies of a Bygone Age by Wooden Vessels',
    },
    {
      albumId: '578722557',
      label: 'Meadowtrek Woods: Life and Ecology - 2023',
      link: 'https://cavebirdrecords.bandcamp.com/album/meadowtrek-woods-life-and-ecology',
      linkLabel: 'Meadowtrek Woods: Life and Ecology by Wooden Vessels',
    },
    {
      albumId: '3277503005',
      label: 'The Beloved Emperor - 2023',
      link: 'https://cavebirdrecords.bandcamp.com/album/the-beloved-emperor',
      linkLabel: 'The Beloved Emperor by Wooden Vessels',
    },
    {
      albumId: '3395428764',
      label: 'To Slumber Beneath a Blanket of White  - 2023',
      link: 'https://cavebirdrecords.bandcamp.com/album/to-slumber-beneath-a-blanket-of-white',
      linkLabel: 'To Slumber Beneath a Blanket of White by Wooden Vessels',
    },
    {
      albumId: '3945216184',
      label: 'Abandoned Crypt of the Blasphemous Lord - 2022',
      link: 'https://cavebirdrecords.bandcamp.com/album/abandoned-crypt-of-the-blasphemous-lord',
      linkLabel: 'Abandoned Crypt of the Blasphemous Lord by Wooden Vessels',
    },
  ],
};

export const dungeonVaultAlbums = {
  amethyst_dagger: {
    albumId: '2171565932',
    artist: 'Amethyst Dagger',
    label: 'The Amethyst Dagger EP / The Judgement of the Moon - 2021',
    link: 'https://gulikrecords.bandcamp.com/album/the-amethyst-dagger-ep-the-judgement-of-the-moon-glk-053',
    linkLabel:
      'The Amethyst Dagger EP / The Judgement of the Moon by Amethyst Dagger',
  },
  'an_old_witch’s_hat': {
    albumId: '4081667564',
    artist: 'An Old Witch’s Hat',
    label: 'A Pact of Warlock Tears and Lycanthropic Divinity - 2023',
    link: 'https://serpentsswordrecords.bandcamp.com/album/a-pact-of-warlock-tears-and-lycanthropic-divinity',
    linkLabel:
      'A Pact of Warlock Tears and Lycanthropic Divinity by An Old Witch’s Hat',
  },
  ancient_boreal_forest: {
    albumId: '4027050997',
    artist: 'Ancient Boreal Forest',
    label: 'Cold Ethereal Winter - 2017',
    link: 'https://ancientborealforest.bandcamp.com/album/cold-ethereal-winter',
    linkLabel: 'Cold Ethereal Winter by Ancient Boreal Forest',
  },
  ancient_invocations: {
    albumId: '4261526893',
    artist: 'Ancient Invocations',
    label: 'Solitude in a Starry Sky - 2023',
    link: 'https://ancientinvocations.bandcamp.com/album/solitude-in-a-starry-sky',
    linkLabel: 'Solitude in a Starry Sky by Ancient Invocations',
  },
  archmast: {
    albumId: '3800077581',
    artist: 'Archmast',
    label: 'As the Wind Carries Us - 2023',
    link: 'https://archmast.bandcamp.com/album/as-the-wind-carries-us',
    linkLabel: 'As the Wind Carries Us by Archmast',
  },
  atlantean_sword: {
    albumId: '3391845468',
    artist: 'Atlantean Sword',
    label: 'Cimmerian Solitude - 2023',
    link: 'https://atlanteansword.bandcamp.com/album/atlantean-sword-cimmerian-solitude-demo-mmxxiii',
    linkLabel:
      'Atlantean Sword - Cimmerian Solitude (Demo) MMXXIII by Atlantean Sword',
  },
  bakt: {
    albumId: '1901491086',
    artist: 'Bakt',
    label: 'Cores de Arquea - 2023',
    link: 'https://bakt.bandcamp.com/album/cores-de-arquea',
    linkLabel: 'Cores de Arquea by Bakt',
  },
  bartizan_chill: {
    albumId: '4031759563',
    artist: 'Bartizan Chill',
    label: 'I Was Cleansed At Aquae Sulis - 2026',
    link: 'https://bartizanchill.bandcamp.com/album/i-was-cleansed-at-aquae-sulis',
    linkLabel: 'I Was Cleansed At Aquae Sulis by Bartizan Chill',
  },
  brave_knight: {
    albumId: '870502637',
    artist: 'Brave Knight',
    label: 'The Adventures of Percival and Montague - 2022',
    link: 'https://braveknight.bandcamp.com/album/the-adventures-of-percival-and-montague',
    linkLabel: 'The Adventures of Percival and Montague by Brave Knight',
  },
  candle_void: {
    albumId: '1070560441',
    artist: 'Candle Void',
    label: 'Candle Void - 2025',
    link: 'https://candlevoid.bandcamp.com/album/candle-void',
    linkLabel: 'Candle Void by Candle Void',
  },
  castle_waters: {
    albumId: '890223950',
    artist: 'Castle Waters',
    label: 'Ethereal Elegance - 2025',
    link: 'https://theastralrealms.bandcamp.com/album/ethereal-elegance',
    linkLabel: 'Ethereal Elegance by Castle Waters',
  },
  chanterelle: {
    albumId: '3220478371',
    artist: 'Chanterelle',
    label: 'Tales from the Forest Floor - 2021',
    link: 'https://chanterelle.bandcamp.com/album/tales-from-the-forest-floor',
    linkLabel: 'Tales from the Forest Floor by Chanterelle',
  },
  chestnut_brown: {
    albumId: '366462984',
    artist: 'Chestnut Brown',
    label: 'Sequoia - 2022',
    link: 'Sequoia',
    linkLabel: 'Sequoia by Chestnut Brown',
  },
  depressive_silence: {
    albumId: '2099193775',
    artist: 'Depressive Silence',
    label: 'Depressive Silence II - 1996',
    link: 'https://a-spell-enraged.bandcamp.com/album/mourning-remastered',
    linkLabel: 'Mourning (remastered) by DEPRESSIVE SILENCE',
  },
  descort: {
    albumId: '160826441',
    artist: 'Descort',
    label: 'Ysopet 1er - 2021',
    link: 'https://descort.bandcamp.com/album/ysopet-1er',
    linkLabel: 'Ysopet 1er by Descort',
  },
  desolation_plains: {
    albumId: '4130170394',
    artist: 'Desolation Plains',
    label: 'Celestial Sorcery - 2026',
    link: 'https://desolationplains.bandcamp.com/album/celestial-sorcery',
    linkLabel: 'Celestial Sorcery by Desolation Plains',
  },
  desolazione_rurale: {
    albumId: '2164699977',
    artist: 'Desolazione Rurale',
    label: 'Verso l’alba - 2023',
    link: 'https://desolazionerurale.bandcamp.com/album/verso-lalba',
    linkLabel: 'Verso l’alba by Desolazione Rurale',
  },
  dim: {
    albumId: '2754431056',
    artist: 'DIM',
    label: 'Compendium III - 2020',
    link: 'https://iamdim.bandcamp.com/album/compendium-iii',
    linkLabel: 'Compendium III by DIM',
  },
  diplodocus: {
    albumId: '1154173385',
    artist: 'Diplodocus',
    label: 'Slow And Heavy - 2019',
    link: 'https://diplodocus.bandcamp.com/album/slow-and-heavy',
    linkLabel: 'Slow And Heavy by Diplodocus',
  },
  dusklight: {
    albumId: '1747122653',
    artist: 'Dusklight',
    label: 'Key XIV - 2023',
    link: 'https://windkeytapes.bandcamp.com/album/key-xiv-enchantment-serenity',
    linkLabel: 'Key XIV: Enchantment &amp; Serenity by Dusklight',
  },
  emglev: {
    albumId: '1833799015',
    artist: 'Emglev',
    label: 'Dor An Tenvalijenn - 2022 (demo from 1994)',
    link: 'https://ancientmeadow.bandcamp.com/album/dor-an-tenvalijenn',
    linkLabel: 'Dor An Tenvalijenn by Emglev',
  },
  ephemerus: {
    albumId: '2781382904',
    artist: 'Ephemerus',
    label: 'Ephemera II - 2022',
    link: 'https://disquieting.bandcamp.com/album/ephemera-ii',
    linkLabel: 'Ephemera II by Ephemerus',
  },
  erang: {
    albumId: '3205634662',
    artist: 'Erang',
    label: 'Another World Another Time - 2013',
    link: 'https://erang.bandcamp.com/album/another-world-another-time',
    linkLabel: 'Another World Another Time by Erang',
  },
  erevos: {
    albumId: '2338764097',
    artist: 'Erevos',
    label: 'My Black Desires - 1994',
    link: 'https://erevos.bandcamp.com/album/my-black-desires-promo-1994',
    linkLabel: 'My Black Desires by Erevos',
  },
  erythrite_throne: {
    albumId: '1905769229',
    artist: 'Erythrite Throne',
    label: 'Through Caliginous Tombs Where Pale Horses Dream - 2022',
    link: 'https://serpentsswordrecords.bandcamp.com/album/through-caliginous-tombs-where-pale-horses-dream',
    linkLabel:
      'Through Caliginous Tombs Where Pale Horses Dream by Erythrite Throne',
  },
  estoc: {
    albumId: '2226416085',
    artist: 'ESTOC',
    label: 'Chapter I - 2019',
    link: 'https://estoc1.bandcamp.com/album/chapter-i',
    linkLabel: 'Chapter I by ESTOC',
  },
  fenmoss: {
    albumId: '3531789836',
    artist: 'Fenmoss',
    label: 'Reawakened Wisdom - 2024',
    link: 'https://barony-of-fenmoss.bandcamp.com/album/reawakened-wisdom',
    linkLabel: 'Reawakened Wisdom by Fenmoss',
  },
  fief: {
    albumId: '3763192730',
    artist: 'Fief',
    label: 'II - 2016',
    link: 'https://fief.bandcamp.com/album/ii',
    linkLabel: 'II by Fief',
  },
  fogweaver: {
    albumId: '4181215458',
    artist: 'Fogweaver',
    label: 'Vedurnan - 2020',
    link: 'https://thefogweaver.bandcamp.com/album/vedurnan',
    linkLabel: 'Vedurnan by Fogweaver',
  },
  forgotten_phantasm: {
    albumId: '2387182410',
    artist: 'Forgotten Phantasm',
    label: '♜♜♜♜♜♜♜ - 2024',
    link: 'https://forgottenphantasm.bandcamp.com/album/-',
    linkLabel: '♜♜♜♜♜♜♜ by Forgotten Phantasm',
  },
  forlorn: {
    albumId: '3237544710',
    artist: 'Forlorn',
    label: 'Forlorn - 2024',
    link: 'https://forlorn-ds.bandcamp.com/album/forlorn',
    linkLabel: 'Forlorn by Forlorn',
  },
  frogknight: {
    albumId: '586575843',
    artist: 'Frogknight',
    label: 'Lothlórien - 2024',
    link: 'https://frogknight.bandcamp.com/album/lothl-rien',
    linkLabel: 'Lothlórien by Frogknight',
  },
  frostgard: {
    albumId: '2721127097',
    artist: 'Frostgard',
    label: 'Valaquenta I - 2021',
    link: 'https://frostgard-dungeonsynth.bandcamp.com/album/valaquenta-i',
    linkLabel: 'Valaquenta I by Frostgard',
  },
  gargoylium: {
    albumId: '354537695',
    artist: 'Gargoylium',
    label: 'Mon Royaume - 2018',
    link: 'https://gargoylium.bandcamp.com/album/mon-royaume',
    linkLabel: 'Mon Royaume by Gargoylium',
  },
  gelure: {
    albumId: '255396186',
    artist: 'Gelure',
    label: 'The Candlelight Tomes - 2021',
    link: 'https://gelure.bandcamp.com/album/the-candlelight-tomes',
    linkLabel: 'The Candlelight Tomes by Gelure',
  },
  gorgons_alter: {
    albumId: '3261724646',
    artist: 'Gorgons Alter',
    label: 'Arcane and Abel - 2024',
    link: 'https://gorgonsalter.bandcamp.com/album/arcane-and-abel',
    linkLabel: 'Arcane and Abel by Gorgons Alter',
  },
  herdade: {
    albumId: '1080988963',
    artist: 'Herdade',
    label: 'Livro Primeiro - 2022',
    link: 'https://herdade.bandcamp.com/album/livro-primeiro',
    linkLabel: 'Livro Primeiro by Herdade',
  },
  hermit_knight: {
    albumId: '318911255',
    artist: 'Hermit Knight',
    label: 'adventures in depersonalization - 2023',
    link: 'https://hermitknight.bandcamp.com/album/adventures-in-depersonalization',
    linkLabel: 'adventures in depersonalization by Hermit Knight',
  },
  hibernal_harvest: {
    albumId: '4152867053',
    artist: 'Hibernal Harvest',
    label: 'Dreamspire - 2023',
    link: 'https://hibernalharvest.bandcamp.com/album/dreamspire',
    linkLabel: 'Dreamspire by Hibernal Harvest',
  },
  hircine: {
    albumId: '1214115397',
    artist: 'Hircine',
    label: 'Old Kings Fall - 2022',
    link: 'https://songsofhircine.bandcamp.com/album/old-kings-fall',
    linkLabel: 'Old Kings Fall by Hircine',
  },
  hjartans: {
    albumId: '4114641268',
    artist: 'Hjartans',
    label: 'Open your heart to the Night - 2024',
    link: 'https://hjartans.bandcamp.com/album/open-your-heart-to-the-night',
    linkLabel: 'Open your heart to the Night by Hjartans',
  },
  hyperborean_might: {
    albumId: '3522688156',
    artist: 'Hyperborean Might',
    label: 'Within The Age Of Savagery - 2023',
    link: 'https://ithildintapeproduction.bandcamp.com/album/within-the-age-of-savagery',
    linkLabel: 'Within The Age Of Savagery by Hyperborean Might',
  },
  inlustris: {
    albumId: '1521929972',
    artist: 'Inlustris',
    label: 'Rosa Das Rosas - 2022',
    link: 'https://inlustris.bandcamp.com/album/rosa-das-rosas',
    linkLabel: 'Rosa Das Rosas by Inlustris',
  },
  jenn_taiga: {
    albumId: '2120946176',
    artist: 'Jenn Taiga',
    label: 'Sanguine Descent - 2025',
    link: 'https://jenntaiga.bandcamp.com/album/sanguine-descent',
    linkLabel: 'Sanguine Descent by Jenn Taiga',
  },
  kyvon: {
    albumId: '2426135048',
    artist: 'Kyvon',
    label: 'Courtier - 2023',
    link: 'https://kyvon.bandcamp.com/album/courtier',
    linkLabel: 'Courtier by Kyvon',
  },
  lone_sentinel: {
    albumId: '2969878331',
    artist: 'Lone Sentinel',
    label: 'Vampyric Obsolescence - 2025',
    link: 'https://hammerandflailrecordings.bandcamp.com/album/vampyric-obsolescence',
    linkLabel: 'Vampyric Obsolescence by Lone Sentinel',
  },
  lore_arborea: {
    albumId: '1065944075',
    artist: 'Lore Arborea',
    label: 'Rivers - 2026',
    link: 'https://lorearborea.bandcamp.com/album/rivers',
    linkLabel: 'Rivers by Lore Arborea',
  },
  the_loreseeker: {
    albumId: '2815154567',
    artist: 'The Loreseeker',
    label: 'Where the Moonlight Herb Grows - 2020',
    link: 'https://theloreseeker.bandcamp.com/album/where-the-moonlight-herb-grows',
    linkLabel: 'Where the Moonlight Herb Grows by The Loreseeker',
  },
  lugubrious_chant: {
    albumId: '167600791',
    artist: 'Lugubrious Chant',
    label: 'Macabre Aurae - 2020',
    link: 'https://lugubriouschant.bandcamp.com/album/macabre-aurae',
    linkLabel: 'Macabre Aurae by Lugubrious Chant',
  },
  lunar_gate: {
    albumId: '501573589',
    artist: 'Lunar Gate',
    label: 'A Secret Well Kept - 1996',
    link: 'https://irish-metal.bandcamp.com/album/lunar-gate-a-secret-well-kept-demo-1996',
    linkLabel: 'A Secret Well Kept by Lunar Gate',
  },
  lunar_womb: {
    albumId: '1930718337',
    artist: 'Lunar Womb',
    label: 'The Sleeping Green - 1999',
    link: 'https://worldoftrollhorn.bandcamp.com/album/the-sleeping-green',
    linkLabel: 'The Sleeping Green by Lunar Womb',
  },
  moonkeeper: {
    albumId: '3865733876',
    artist: 'MoonKeeper',
    label: 'The Keeper’s Odyssey - 2023',
    link: 'https://moonkeeper.bandcamp.com/album/the-keepers-odyssey',
    linkLabel: 'The Keeper’s Odyssey by MoonKeeper',
  },
  moonkissed_spires: {
    albumId: '1454872167',
    artist: 'Moonkissed Spires',
    label: 'Hymns of the Battlefield - 2024',
    link: 'https://moonkissedspires.bandcamp.com/album/hymns-of-the-battlefield',
    linkLabel: 'Hymns of the Battlefield by Moonkissed Spires',
  },
  mordiford_dragon: {
    albumId: '136601526',
    artist: 'Mordiford Dragon',
    label: 'The Tale of the Mordiford Dragon Part I - 2022',
    link: 'https://mordiforddragon.bandcamp.com/album/the-tale-of-the-mordiford-dragon-part-i',
    linkLabel: 'The Tale of the Mordiford Dragon Part I by Mordiford Dragon',
  },
  nan_morlith: {
    albumId: '2989012696',
    artist: 'Nan Morlith',
    label: 'Âdhûn & Fangorn - 2020',
    link: 'https://nanmorlith.bandcamp.com/album/dh-n-fangorn',
    linkLabel: 'Âdhûn & Fangorn by Nan Morlith',
  },
  nest: {
    albumId: '2433808251',
    artist: 'Nest',
    label: 'Hidden Stream - 2001',
    link: 'https://nestfin.bandcamp.com/album/hidden-stream',
    linkLabel: 'Hidden Stream by Nest',
  },
  oublieth: {
    albumId: '471073603',
    artist: 'Oublieth',
    label: 'Uren Vell - 2024',
    link: 'https://oublieth.bandcamp.com/album/uren-vell',
    linkLabel: 'Uren Vell by Oublieth',
  },
  porcelain_sword: {
    albumId: '2983422098',
    artist: 'Porcelain Sword',
    label: 'Porcelain Sword - 2023',
    link: 'https://porcelainsword.bandcamp.com/album/porcelain-sword',
    linkLabel: 'Porcelain Sword by Porcelain Sword',
  },
  refusa: {
    albumId: '3025787786',
    artist: 'Refusa',
    label: 'In Muck and Mire | Turned to Sludge - 2024',
    link: 'https://refusa.bandcamp.com/album/in-muck-and-mire-turned-to-sludge',
    linkLabel: 'In Muck and Mire | Turned to Sludge by Refusa',
  },
  rog: {
    albumId: '1783752788',
    artist: 'Rog',
    label: 'Brave sir Robin - 2018',
    link: 'https://rogofficial.bandcamp.com/album/brave-sir-robin',
    linkLabel: 'Brave sir Robin by Rog',
  },
  secret_stairways: {
    albumId: '225886347',
    artist: 'Secret Stairways',
    label: 'Turning Point - 1999',
    link: 'https://secretstairways.bandcamp.com/album/turning-point',
    linkLabel: 'Turning Point by Secret Stairways',
  },
  sequestered_keep: {
    albumId: '2116089096',
    artist: 'Sequestered Keep',
    label: 'The Oldest Realm - 2016',
    link: 'https://sequesteredkeep.bandcamp.com/album/the-oldest-realm',
    linkLabel: 'The Oldest Realm by Sequestered Keep',
  },
  silent_garden: {
    albumId: '3210086173',
    artist: 'Silent Garden',
    label: 'Demo II - 2022',
    link: 'https://silentgardenmusic.bandcamp.com/album/demo-ii',
    linkLabel: 'Demo II by Silent Garden',
  },
  soltri: {
    albumId: '2067937489',
    artist: 'Soltri',
    label: 'The Rising of the King Arthur - 2017',
    link: 'https://soltri.bandcamp.com/album/the-rising-of-the-king-arthur',
    linkLabel: 'The Rising of the King Arthur by Soltri',
  },
  sorrowmoon: {
    albumId: '159520955',
    artist: 'Sorrowmoon',
    label: 'Sorrowmoon - 2024',
    link: 'https://sorrowmoon.bandcamp.com/album/sorrowmoon',
    linkLabel: 'Sorrowmoon by Sorrowmoon',
  },
  sourcerior: {
    albumId: '3365241793',
    artist: 'Sourcerior',
    label: 'Messère - 2022',
    link: 'https://sourcerior.bandcamp.com/album/mess-re',
    linkLabel: 'Messère by Sourcerior',
  },
  spectral_austräa: {
    albumId: '591195171',
    artist: 'Spectral Austräa',
    label: 'Solemn Spring - 2024',
    link: 'https://spectralaustraa.bandcamp.com/album/solemn-spring',
    linkLabel: 'Solemn Spring by Spectral Austräa',
  },
  spellbound_mire: {
    albumId: '2484794722',
    artist: 'Spellbound Mire',
    label: 'Spellbound Mire - 2022',
    link: 'https://spellboundmire.bandcamp.com/album/spellbound-mire',
    linkLabel: 'Spellbound Mire by Spellbound Mire',
  },
  spife: {
    albumId: '3139651231',
    artist: 'Spife',
    label: 'The Fulfillment of The ’Scapen - 2023',
    link: 'https://spife-dot-mp4.bandcamp.com/album/the-fulfillment-of-the-scapen',
    linkLabel: 'The Fulfillment of The ’Scapen by Spife',
  },
  swordcerer: {
    albumId: '2593179938',
    artist: 'Swordcerer',
    label: 'A September Night’s Dream by Swordcerer - 2025',
    link: 'https://swordcerer.bandcamp.com/album/a-september-nights-dream',
    linkLabel: 'A September Night’s Dream by Swordcerer by Swordcerer',
  },
  sylfvr: {
    albumId: '3286080536',
    artist: 'Sylfvr',
    label: 'A Nice Evening Stroll - 2024',
    link: 'https://sylfvr.bandcamp.com/album/a-nice-evening-stroll',
    linkLabel: 'A Nice Evening Stroll by Sylfvr',
  },
  sylvan_echoes: {
    albumId: '708562239',
    artist: 'Sylvan Echoes',
    label: 'I - 2021',
    link: 'https://sylvanechoes.bandcamp.com/album/i',
    linkLabel: 'I by Sylvan Echoes',
  },
  thangorodrim: {
    albumId: '586827447',
    artist: 'Thangorodrim',
    label: 'Akallabêth - 2018',
    link: 'https://thangorodrimsynth.bandcamp.com/album/akallab-th-ep',
    linkLabel: 'Akallabêth by Thangorodrim',
  },
  that_demon_the_sun: {
    albumId: '4250056751',
    artist: 'That Demon The Sun',
    label: 'Ghosted - 2023',
    link: 'https://hadeanhollerrecordings.bandcamp.com/album/ghosted',
    linkLabel: 'Ghosted by That Demon the Sun',
  },
  til_det_bergens_skyggene: {
    albumId: '3293959707',
    artist: 'Til Det Bergens Skyggene',
    label: 'Til Det Bergens Skyggene - 2011',
    link: 'https://voldsomtapes.bandcamp.com/album/til-det-bergens-skyggene',
    linkLabel: 'Til Det Bergens Skyggene by Til Det Bergens Skyggene',
  },
  tree_gardener: {
    albumId: '1982507984',
    artist: 'Tree Gardener',
    label: 'A Pilgrim in the Frozen Wood - 2026',
    link: 'ttps://treegardener.bandcamp.com/album/a-pilgrim-in-the-frozen-wood',
    linkLabel: 'A Pilgrim in the Frozen Wood by Tree Gardener',
  },
  ugrino: {
    albumId: '3898342440',
    artist: 'Ugrino',
    label: 'Miracle - 2023',
    link: 'https://ugrino.bandcamp.com/album/miracle',
    linkLabel: 'Miracle by Ugrino',
  },
  ulk: {
    albumId: '1014444236',
    artist: 'ulk',
    label: 'Restoration Magic - 2022',
    link: 'https://ulkmusic.bandcamp.com/album/restoration-magic',
    linkLabel: 'Restoration Magic by ulk',
  },
  under_the_frost_moon: {
    albumId: '2650200803',
    artist: 'Unsheathed Glory',
    label: 'The Forest of Forgotten Dreams - 2024',
    link: 'https://underthefrostmoon.bandcamp.com/album/the-forest-of-forgotten-dreams',
    linkLabel: 'The Forest of Forgotten Dreams by Under the Frost Moon',
  },
  unsheathed_glory: {
    albumId: '2087741473',
    artist: 'Unsheathed Glory',
    label: 'Fables from Featherwood Forest - 2023',
    link: 'https://unsheathedglory.bandcamp.com/album/fables-from-featherwood-forest',
    linkLabel: 'Fables from Featherwood Forest by Unsheathed Glory',
  },
  ur_pale: {
    albumId: '963888117',
    artist: 'Ur Pale',
    label: 'Sea Synth Ensemble - 2017',
    link: 'https://urpalemperor.bandcamp.com/album/sea-synth-ensemble',
    linkLabel: 'Sea Synth Ensemble by Ur Pale',
  },
  vale_minstrel: {
    albumId: '2024930507',
    artist: 'Vale Minstrel',
    label: 'Warden Of The Vale - 2020',
    link: 'https://valeminstrel.bandcamp.com/album/warden-of-the-vale',
    linkLabel: 'Warden Of The Vale by Vale Minstrel',
  },
  valor: {
    albumId: '724233733',
    artist: 'Valor',
    label: 'La Lune Noire - 1996',
    link: 'https://darkageproductions.bandcamp.com/album/la-lune-noire',
    linkLabel: 'La Lune Noire by Valor',
  },
  vanhellig: {
    albumId: '3518011199',
    artist: 'Vanhellig',
    label: 'The Ghost in the Spire - 2021',
    link: 'https://vanhellig.bandcamp.com/album/the-ghost-in-the-spire',
    linkLabel: 'The Ghost in the Spire by Vanhellig',
  },
  vanishing_amulet: {
    albumId: '3307847872',
    artist: 'Vanishing Amulet',
    label: 'Nocturnal Heritage - 2022',
    link: 'https://vanishingamulet.bandcamp.com/album/nocturnal-heritage',
    linkLabel: 'Nocturnal Heritage by Vanishing Amulet',
  },
  vermin_halls: {
    albumId: '3472821423',
    artist: 'Vermin Halls',
    label: 'Mourningwraith - 2022',
    link: 'https://pestilent-one.bandcamp.com/album/mourningwraith',
    linkLabel: 'Mourningwraith by Vermin Halls',
  },
  villein: {
    albumId: '413853285',
    artist: 'Villein',
    label: 'Kreis - 2020',
    link: 'https://thevillein.bandcamp.com/album/kreis',
    linkLabel: 'Kreis by Villein',
  },
  vindkaldr: {
    albumId: '3116319128',
    artist: 'Vindkaldr',
    label: 'Enchantments Of Old Lore - 2015',
    link: 'https://vindkaldr.bandcamp.com/album/enchantments-of-old-lore',
    linkLabel: 'Enchantments Of Old Lore by Vindkaldr',
  },
  windspell: {
    albumId: '4223476907',
    artist: 'Windspell',
    label: 'Wilderness Sanctuary - 2023',
    link: 'https://windspell-realm.bandcamp.com/album/wilderness-sanctuary',
    linkLabel: 'Wilderness Sanctuary by Windspell',
  },
  wingthalion: {
    albumId: '2294069635',
    artist: 'Wingthalion',
    label: 'To Find Solace in the Stillness - 2020',
    link: 'https://wingthalion.bandcamp.com/album/to-find-solace-in-the-stillness',
    linkLabel: 'To Find Solace in the Stillness by Wingthalion',
  },
  wooden_lungs: {
    albumId: '3680094735',
    artist: 'Wooden Lungs',
    label: 'Quiet Places - 2023',
    link: 'https://ageofbarbarity.bandcamp.com/album/quiet-places',
    linkLabel: 'Quiet Places by Wooden Lungs',
  },
  zireael: {
    albumId: '4088138630',
    artist: 'Zireael',
    label: 'Upon Her Blade... - 2025',
    link: 'https://arcanechapel.bandcamp.com/album/upon-her-blade',
    linkLabel: 'Upon Her Blade... by Zireael',
  },
};
