export const bandcampAlbums = {
  'awren (atmospheric black metal)': [
    {
      albumId: '1205304009',
      height: '340px',
      label: 'decaying memories - 2022',
      link: 'https://cavebirdrecords.bandcamp.com/album/decaying-memories',
      linkLabel: 'decaying memories by awren',
    },
    {
      albumId: '3536867511',
      height: '241px',
      label: 'Dreams - 2016',
      link: 'https://cavebirdrecords.bandcamp.com/album/dreams',
      linkLabel: 'Dreams by awren',
    },
    {
      albumId: '1621410143',
      height: '274px',
      label: 'A Wren EP - 2009',
      link: 'https://cavebirdrecords.bandcamp.com/album/a-wren-ep',
      linkLabel: 'A Wren EP by awren',
    },
  ],
  'chrysanthemum (ambient guitar)': [
    {
      albumId: '1764876855',
      height: '373px',
      label: 'the softest feeling the quietest touch - 2023',
      link: 'https://cavebirdrecords.bandcamp.com/album/the-softest-feeling-the-quietest-touch',
      linkLabel: 'the softest feeling the quietest touch by chrysanthemum',
    },
    {
      albumId: '492363530',
      height: '373px',
      label: 'Thaw - 2019',
      link: 'https://cavebirdrecords.bandcamp.com/album/thaw',
      linkLabel: 'Thaw by chrysanthemum',
    },
    {
      albumId: '3581577905',
      height: '373px',
      label: 'Journeying From Death to Rebirth - 2015',
      link: 'https://cavebirdrecords.bandcamp.com/album/journeying-from-death-to-rebirth',
      linkLabel: 'Journeying From Death to Rebirth by chrysanthemum',
    },
    {
      albumId: '2028220265',
      height: '373px',
      label: 'chrysanthemum - 2013',
      link: 'https://cavebirdrecords.bandcamp.com/album/chrysanthemum',
      linkLabel: 'chrysanthemum by chrysanthemum',
    },
    {
      albumId: '3285176979',
      height: '373px',
      label: 'A Taste of Things to Come - 2013',
      link: 'https://cavebirdrecords.bandcamp.com/album/a-taste-of-things-to-come',
      linkLabel: 'A Taste of Things to Come by chrysanthemum',
    },
  ],
  'Gloomthread (funeral doom)': [
    {
      albumId: '993920283',
      height: '307px',
      label: 'Shadow Walk - 2018',
      link: 'https://cavebirdrecords.bandcamp.com/album/shadow-walk',
      linkLabel: 'Shadow Walk by Gloomthread',
    },
    {
      albumId: '598059969',
      height: '208px',
      label: 'Winter Kings - 2016',
      link: 'https://cavebirdrecords.bandcamp.com/album/winter-kings',
      linkLabel: 'Winter Kings by Gloomthread',
    },
  ],
  'Wooden Vessels (dungeon synth)': [
    {
      albumId: '578722557',
      height: '406px',
      label: 'Meadowtrek Woods: Life and Ecology - 2023',
      link: 'https://cavebirdrecords.bandcamp.com/album/meadowtrek-woods-life-and-ecology',
      linkLabel: 'Meadowtrek Woods: Life and Ecology by Wooden Vessels',
    },
    {
      albumId: '3277503005',
      height: '340px',
      label: 'The Beloved Emperor - 2023',
      link: 'https://cavebirdrecords.bandcamp.com/album/the-beloved-emperor',
      linkLabel: 'The Beloved Emperor by Wooden Vessels',
    },
    {
      albumId: '3395428764',
      height: '406px',
      label: 'To Slumber Beneath a Blanket of White  - 2023',
      link: 'https://cavebirdrecords.bandcamp.com/album/to-slumber-beneath-a-blanket-of-white',
      linkLabel: 'To Slumber Beneath a Blanket of White by Wooden Vessels',
    },
    {
      albumId: '3945216184',
      height: '340px',
      label: 'Abandoned Crypt of the Blasphemous Lord - 2022',
      link: 'https://cavebirdrecords.bandcamp.com/album/abandoned-crypt-of-the-blasphemous-lord',
      linkLabel: 'Abandoned Crypt of the Blasphemous Lord by Wooden Vessels',
    },
  ],
};
