export const contactData = [
  {
    class: 'contact-info-email',
    href: 'mailto:awren.nuit@gmail.com?subject=I%20Loved%20Your%20Portfolio',
    label: 'awren.nuit@gmail.com',
    method: 'Email',
    rel: null,
    target: null,
  },
  {
    ariaLabel: '6 5 1. 2 7 6. 3 4 6 1.',
    class: 'contact-info-phone',
    href: 'tel:+01-651-276-3461',
    label: '651-276-3461',
    method: 'Phone',
    rel: null,
    target: null,
  },
  {
    class: 'contact-info-github',
    href: 'https://github.com/awrennuit',
    label: 'awrennuit',
    method: 'GitHub',
    rel: 'noopener noreferrer',
    target: '_blank',
  },
  {
    class: 'contact-info-linkedin',
    href: 'https://www.linkedin.com/in/awren-nuit/',
    label: 'awren nuit',
    method: 'LinkedIn',
    rel: 'noopener noreferrer',
    target: '_blank',
  },
];
