export const dungeonVaultArtists = [
  'Ancient Invocations',
  'Archmast',
  'Arvondrakh',
  'Atlantean Sword',
  'Atrium of Time',
  'Bakt',
  'Chanterelle',
  'Deionarra',
  'Depressive Silence',
  'Descort',
  'Desolazione Rurale',
  'DIM',
  'Dusklight',
  'Dust Seeker',
  'Ephemerus',
  'Erang',
  'ESTOC',
  'Fief',
  'Fogweaver',
  'Forgotten Phantasm',
  'Frostgard',
  'Gelure',
  'Herdade',
  'Hibernal Harvest',
  'Hircine',
  'Hyperborean Might',
  'Koryos',
  'Kyvon',
  'The Loreseeker',
  'Losgann',
  'Lost Woods',
  'Lugubrious Chant',
  'Lunar Womb',
  'MoonKeeper',
  'Mordiford Dragon',
  'Morke Og Lys',
  'Morrowsworn',
  'Nan Morlith',
  'Porcelain Sword',
  // 'Relic Bearer', // doesn't work since it's a single tracks
  'Rog',
  'Secret Stairways',
  'Sequestered Keep',
  'Silent Garden',
  'Skhemty',
  'Sourcerior',
  'Spectral Austräa',
  'Spellbound Mire',
  'Spife',
  'Sylvan Echoes',
  'That Demon The Sun',
  'Ugrino',
  'ulk',
  'Unsheathed Glory',
  'Vale Minstrel',
  'Vanishing Amulet',
  'Vermin Halls',
  'Vetraheimr',
  'Villein',
  'Vindkaldr',
  'Windspell',
  'Wingthalion',
  'Wizards of Aldur',
  'Wooden Lungs',
];
