const styleAesthetic = [
  'forest synth',
  'winter synth',
  'old school dungeon synth',
  'medieval folk',
  'comfy synth',
  'dungeon drone',
  'dungeon ambient',
  'sea synth',
  'crypt-hop',
  'wampyric dungeon synth',
  'nature synth',
  'funeral synth',
  'halloween/spooky synth',
];

const albumTheme = [
  'mythical tales of dragons that might not be so mythical after all...',
  'wizards - studying in their tower or embarking on a quest',
  'gnomes living their charmed lives',
  'goblins planning an attack on a nearby settlement',
  'a tale following a few knights; they may be gallant or murderous',
  'life inside the castle’s walls',
  'ships - sailing at sea or recently-exposed wreckage due to drought',
  'exploring a string of caves',
  'what goes on in the dungeon',
  'a perilous adventure',
  'nostalgia & memories',
  'the classic hero journey',
  'a wondrous adventure',
  'in the heat of battle',
  'the kingdom is sorting out how to deal with a recent defeat',
  'sleep/dreams',
  'seeing the future',
  'seeing the past',
  'dwarves toiling away deep beneath the surface',
  'what goes on in the land of the elves?',
  'songs either about deities or in praise of them',
  'magic - mystical, helpful, hurtful, or otherwise',
  'the uses of mushrooms - herbal, medicinal, magical, or otherwise',
  'fairies - an enchanting tale or a tale of their trickery',
  'the forest - is it friendly or sinister?',
  'the mountains - an exploration, adventure, or just the sounds of the mountains',
  'winter tales',
  'spring tales',
  'summer tales',
  'autumn tales',
  'investigating the rumors of mermaids luring sailors to their death',
  'demons - imps, devils, and other evil magical creatures',
  'the dead have began to walk to earth...and have a dance party',
  'local giants have a debt to the farmers - how did this come to be?',
  'trolls seeking to live among the humans',
  'a band of orcs have launched a rebellion against their leaders',
  'what have the centaurs been up to?',
  'from the perspective of the mythical birds that soar the skies',
  'an ancient golem that has been living in isolation for centuries',
  'a bullheaded barbarian who frequently gets his party into trouble',
  'a fast-talking rogue who gets his party out of trouble',
  'an introspective mage who can see the outcome of the battle before it begins',
  'a cunning ranger adept at gathering intel from dangerous places',
  'a diplomatic druid who excels at resolving wars',
  'a found letter/recording detailing something mysterious that’s going on',
  'exploring an abandoned village',
  'you stumble upon a collection of assorted cursed objects',
  'the effects of the mystical potion you just drank',
  'reincarnation is real, but only for the most oppressed - this leads to everyone trying to be oppressed',
  'entering a portal/doorway/mirror/window/etc to another world',
  'a prophecy coming to pass',
  'a traveler passing through town - they might be mysterious, nefarious, or righteous',
  'waking up and finding out that 50 years have passed',
  'ghosts - they may be haunting something or someone, confused about where they are, thinking they’re still alive, or something else',
  'a world where the dream world & waking world overlap',
  'someone with extremely good luck',
  'someone with extremely bad luck',
  'alchemy - perhaps an alchemist’s experiments, the history of alchemy, or something else',
  'life at the cottage on the cliffside',
  'the desert - such as exploring it, conquering it, getting lost in it',
  'numerology - what could certain numbers mean?',
  'tarot - perhaps individual cards or the events that unfold after a reading',
  'astrology & the cosmos',
  'myths & legends',
  'a merchant travelling from town to town - no one knows where the merchant comes from and no one has seen the merchant’s face',
  'discovering a long-forgotten city',
  'a cozy night of celebrations at the tavern',
  'a group of adventurers are ambushed by goblins...who want to party with them',
  'the largest tree in the forest is rumored to contain a secret...',
  'you discover an ancient tomb sealed by magic',
  'life at the ogre sanctuary',
  'battle-hardened pirates sailing the high seas in search of true love',
];

const special = [
  'incorporate field recordings into each song',
  'use acoustic guitar as main instrument',
  'use acoustic piano as main instrument',
  'use acoustic harp as main instrument',
  'use only four instruments',
  'the album must have four songs',
  'the album must be completed in 21 days (instead of 14)',
  'base the album on public domain artwork & use this artwork on the album’s cover art',
  'base the album on poem or one page story (your own or someone else’s)',
  'base the album on a place you’ve been to',
  'make heavy use of reverb',
  'add at least a little bit of distortion to each instrument',
  'add at least a little bit of chorus to each instrument',
  'drums must be present in each song',
  'drums cannot be used in any song',
  'at least two songs must be in an odd meter (5/4, 7/8, etc)',
  'use a reversed audio effect in each song',
  'incorporate silence into at least two songs',
  'use only four notes in at least one song (ex: C, D, G, A; can use these notes in any octave)',
  'create a musical ‘theme’ or ‘motif’ that is used in at least half the songs (ex: a short melody or series of notes)',
  'base at least two songs on a loop that plays throughout those songs',
  'use instruments in unconventional ways (ex: drums for melody, clarinet for bass, synth lead for drums, etc)',
  'use a VST like synth1 or Dexed to create your own custom sound(s)',
  'at least one song must be under one minute long',
  'at least one song must be over five minutes long',
  'utilize volume & velocity to create a dynamic range of loud and quiet throughout the album',
  'incoporate spoken word into each song',
];

export { albumTheme, special, styleAesthetic };
