export const dungeonVaultArtists = [
  'Ancient Boreal Forest',
  'Ancient Invocations',
  'Archmast',
  'Arvondrakh',
  'Atlantean Sword',
  'Atrium of Time',
  'Bakt',
  'Bartizan Chill',
  'Chanterelle',
  'Deionarra',
  'Depressive Silence',
  'Descort',
  'Desolazione Rurale',
  'DIM',
  'Diplodocus',
  'Dusklight',
  'Dust Seeker',
  'Ephemerus',
  'Erang',
  'ESTOC',
  'Fenmoss',
  'Fief',
  'Fogweaver',
  'Forgotten Phantasm',
  'Forlorn',
  'Frostgard',
  'Gelure',
  'Gorgons Alter',
  'Herdade',
  'Hermit Knight',
  'Hibernal Harvest',
  'Hircine',
  'Hjartans',
  'Hyperborean Might',
  'Koryos',
  'Kyvon',
  'Lone Sentinel',
  'The Loreseeker',
  'Losgann',
  'Lost Woods',
  'Lugubrious Chant',
  'Lunar Womb',
  'Maximum Mana',
  'MoonKeeper',
  'Moonkissed Spires',
  'Mordiford Dragon',
  'Morke Og Lys',
  'Morrowsworn',
  'Nan Morlith',
  'Porcelain Sword',
  // 'Relic Bearer', // doesn't work since it's a single tracks
  'Rog',
  'Secret Stairways',
  'Sequestered Keep',
  'Silent Garden',
  'Skhemty',
  'Sourcerior',
  'Spectral Austräa',
  'Spellbound Mire',
  'Spife',
  'Sylvan Echoes',
  'That Demon The Sun',
  'Ugrino',
  'ulk',
  'Unsheathed Glory',
  'Vale Minstrel',
  'Vanishing Amulet',
  'Vermin Halls',
  'Vetraheimr',
  'Villein',
  'Vindkaldr',
  'Windspell',
  'Wingthalion',
  'Wizards of Aldur',
  'Wooden Lungs',
];
