export const dungeonVaultArtists = [
  'Amethyst Dagger',
  'An Old Witch’s Hat',
  'Ancient Boreal Forest',
  'Ancient Invocations',
  'Archmast',
  'Atlantean Sword',
  'Bakt',
  'Bartizan Chill',
  'Brave Knight',
  'Candle Void',
  'Castle Waters',
  'Chanterelle',
  'Chestnut Brown',
  'Depressive Silence',
  'Descort',
  'Desolation Plains',
  'Desolazione Rurale',
  'DIM',
  'Diplodocus',
  'Dusklight',
  'Emglev',
  'Ephemerus',
  'Erang',
  'Erevos',
  'Erythrite Throne',
  'ESTOC',
  'Fenmoss',
  'Fief',
  'Fogweaver',
  'Forgotten Phantasm',
  'Forlorn',
  'Frogknight',
  'Frostgard',
  'Gargoylium',
  'Gelure',
  'Gorgons Alter',
  'Herdade',
  'Hermit Knight',
  'Hibernal Harvest',
  'Hircine',
  'Hjartans',
  'Hyperborean Might',
  'Inlustris',
  'Jenn Taiga',
  'Kyvon',
  'Lone Sentinel',
  'Lore Arborea',
  'The Loreseeker',
  'Lugubrious Chant',
  'Lunar Gate',
  'Lunar Womb',
  'MoonKeeper',
  'Moonkissed Spires',
  'Mordiford Dragon',
  'Nan Morlith',
  'Nest',
  'Oublieth',
  'Porcelain Sword',
  'Refusa',
  'Rog',
  'Secret Stairways',
  'Sequestered Keep',
  'Silent Garden',
  'Soltri',
  'Sorrowmoon',
  'Sourcerior',
  'Spectral Austräa',
  'Spellbound Mire',
  'Spife',
  'Swordcerer',
  'Sylfvr',
  'Sylvan Echoes',
  'Thangorodrim',
  'That Demon The Sun',
  'Til Det Bergens Skyggene',
  'Tree Gardener',
  'Ugrino',
  'ulk',
  'Under the Frost Moon',
  'Unsheathed Glory',
  'Ur Pale',
  'Vale Minstrel',
  'Valor',
  'Vanhellig',
  'Vanishing Amulet',
  'Vermin Halls',
  'Villein',
  'Vindkaldr',
  'Windspell',
  'Wingthalion',
  'Wooden Lungs',
  'Zireael',
];
