const styleAesthetic = [
  'forest synth',
  'battle/war synth',
  'winter synth',
  'epic dungeon synth',
  'old school dungeon synth',
  'medieval folk',
  'desert synth',
  'dark dungeon synth',
  'comfy synth',
  'gnome synth',
  'dungeon drone',
  'astral dungeon synth',
  'romantic dungeon synth',
  'sci-fi dungeon synth',
  'dungeon ambient',
  'mushroom synth',
  'raw dungeon synth',
  'sea synth',
  'crypt-hop',
  'primitive dungeon synth',
  'dream synth',
  'wampyric dungeon synth',
  'nature synth',
  'dino synth',
  'funeral synth',
  'barbarian synth',
  'halloween/spooky synth',
  'castle synth',
  'pastoral synth',
  'cosmic synth',
  'horror synth',
  'new age',
  'dungeon step',
  'dragon synth',
  'goblin synth',
  'lo-fi synth',
  'tavern synth',
  'orchestral synth',
  'coastal synth',
  'hill synth',
  'plague synth',
  'adventure synth',
  'ethereal synth',
  'foggy/misty synth',
  'radiant synth',
  'earthen synth',
  'cold synth',
  'chip synth',
  'chill synth',
  'macabre synth',
  'nautical synth',
  'gloom synth',
  'rustic synth',
  'rural synth',
  'serfdom synth',
  'sanguine synth',
  'therapeutic synth',
  'spectral synth',
  'vapor synth',
  'portal synth',
  'verdant synth',
  'sanctuary synth',
  'chaos synth',
  'monk synth',
  'meditative synth',
  'magick synth',
  'reliquary synth',
  'rogue synth',
  'mystic synth',
  'river synth',
  'abyssal synth',
  'arcane synth',
  'bog synth',
  'elven synth',
  'tower synth',
  'wanderer synth',
  'merchant synth',
  'solar synth',
  'fairytale synth',
  'folklore synth',
  'mechasynth',
  'ghostly synth',
  'monastic synth',
  'jester synth',
  'royal synth',
  'nocturnal synth',
  'enlightened synth',
  'mundane synth',
  'background synth',
  'mythic synth',
  'leisure synth',
  'marauder synth',
  'pirate synth',
  'meadow synth',
  'wind synth',
  'noble synth',
  'lunar synth',
  'dishonorable synth',
  'shield synth',
  'marketplace synth',
  'farm synth',
  'economic synth',
  'mortuary synth',
  'nomadic synth',
  'gentry synth',
  'animistic synth',
  'rain synth',
  'heretic synth',
  'apostate synth',
  'beggar synth',
  'necromantic synth',
  'mid-day synth',
  'pantheon synth',
  'potion synth',
  'shopkeep synth',
  'prophetic synth',
  'questing synth',
  'dungeon doom',
  'quill & parchment synth',
  'gemstone synth',
  'runic synth',
  'regal synth',
  'storm synth',
  'shadow synth',
  'elemental synth',
  'spell synth',
  'skirmish synth',
  'sword synth',
  'umbral synth',
  'visionary synth',
  'witch synth',
  'orc synth',
  'dwarven synth',
];

const albumTheme = [
  'mythical tales of dragons that might not be so mythical after all...',
  'wizards - studying in their tower or embarking on a quest.',
  'gnomes living their charmed lives.',
  'goblins planning an attack on a nearby settlement.',
  'a tale following a few knights; they may be gallant or murderous.',
  'life inside the castle’s walls.',
  'ships - sailing at sea or recently-exposed wreckage due to drought.',
  'exploring a string of caves.',
  'what goes on in the dungeon.',
  'a perilous adventure.',
  'nostalgia & memories.',
  'the classic hero journey.',
  'a wondrous adventure.',
  'in the heat of battle.',
  'the kingdom is sorting out how to deal with a recent defeat.',
  'sleep/dreams.',
  'seeing the future.',
  'seeing the past.',
  'dwarves toiling away deep beneath the surface.',
  'what goes on in the land of the elves?',
  'songs either about deities or in praise of them.',
  'magic - mystical, helpful, hurtful, or otherwise.',
  'the uses of mushrooms - herbal, medicinal, magical, or otherwise.',
  'fairies - an enchanting tale or a tale of their trickery.',
  'the forest - is it friendly or sinister?',
  'the mountains - an exploration, adventure, or just the sounds of the mountains.',
  'winter tales.',
  'spring tales.',
  'summer tales.',
  'autumn tales.',
  'investigating the rumors of mermaids luring sailors to their death.',
  'demons - imps, devils, and other evil magical creatures.',
  'the dead have began to walk to earth...and have a dance party.',
  'local giants have a debt to the farmers - how did this come to be?',
  'trolls seeking to live among the humans.',
  'a band of orcs have launched a rebellion against their leaders.',
  'what have the centaurs been up to?',
  'the world is ending - what does it look like? how do the people react?',
  'from the perspective of the mythical birds that soar the skies.',
  'an ancient golem that has been living in isolation for centuries.',
  'a bullheaded barbarian who frequently gets his party into trouble.',
  'a fast-talking rogue who gets his party out of trouble.',
  'an introspective mage who can see the outcome of the battle before it begins.',
  'a cunning ranger adept at gathering intel from dangerous places.',
  'a diplomatic druid who excels at resolving wars.',
  'a found letter/recording detailing something mysterious that’s going on.',
  'exploring an abandoned village.',
  'you stumble upon a collection of assorted cursed objects.',
  'the effects of the mystical potion you just drank.',
  'a mighty warrior has been afflicted by a terrible illness and has to adapt to his new life',
  'reincarnation is real, but only for the most oppressed - this leads to everyone trying to be oppressed.',
  'entering a portal/doorway/mirror/window/etc to another world.',
  'a prophecy coming to pass.',
  'a traveler passing through town - they might be mysterious, nefarious, or righteous.',
  'waking up and finding out that 50 years have passed.',
  'ghosts - they may be haunting something or someone, confused about where they are, thinking they’re still alive, or something else.',
  'a land where the dream realm & waking world overlap.',
  'a plague has swept through the land...and you are tasked with finding its source',
  'someone with extremely good luck.',
  'someone with extremely bad luck.',
  'something is lurking in the heavy fog...',
  'alchemy - perhaps an alchemist’s experiments, the history of alchemy, or something else.',
  'life at the cottage on the cliffside.',
  'the desert - such as exploring it, conquering it, getting lost in it.',
  'a young ranger dealing with the sudden loss of their mentor',
  'numerology - what could certain numbers mean?',
  'tarot - perhaps individual cards or the events that unfold after a reading.',
  'astrology & the cosmos.',
  'myths & legends.',
  'a merchant travelling from town to town - no one knows where the merchant comes from and no one has seen the merchant’s face.',
  'discovering a long-forgotten city.',
  'a cozy night of celebrations at the tavern.',
  'a group of adventurers are ambushed by goblins...who want to party with them.',
  'the largest tree in the forest is rumored to contain a secret...',
  'you discover an ancient tomb sealed by magic.',
  'life at the ogre sanctuary.',
  'battle-hardened pirates sailing the high seas in search of true love.',
  'some unruly youth break into a building at night and drink a potion on a dare. now they hear the thoughts of animals. *every* thought.',
  'legend speaks of a woman who united the land. are the myths correct or is there more to the story...?',
  'that which you fear most has been tasked with stalking you.',
  'a science experiment gone terribly wrong.',
  'what happens in the space between our world and the next.',
  'the most unlikely of heroes saves the day in the most unexpected way.',
  'a regular old boring time traveling from one town to the next.',
  'a serene time sailing in familiar waters.',
  'an evil wizard and his secret plot to conquer the land.',
  'you are reminded of your happiest memories and it warms your soul.',
  'what goes on in the abandoned village?',
  'what goes on behind closed doors in the castle?',
  'what goes on in the shadowy citadel?',
  'the evil lord gets a cold and his minions can no longer take him (or her) seriously.',
  'leaving a secret when building the ship - it could be a message, something magical, or something else.',
  'the young wizard is practicing a spell to help his beard grow longer...and it has unexpected effects.',
  'an egotistical archer in danger after his party deserted him.',
  'what *really* happens on adventures - the stories are clearly embellished!',
  'accepting death as you slowly sink in the quicksand, only to realize it leads to a secret room.',
  'the last words of the bandit leader come true.',
  'a paladin and a rogue team up to end the exploitation of the working class...for their own *very different* reasons',
  'a small band of adventurers have been tasked with guarding the caravan as it passes through a dangerous area.',
  'the land of ice & snow’s unseasonably warm weather has uncovered something of interest...',
  'the solar & lunar deities broke up, causing mayhem for the planet’s inhabitants.',
  'the old knight’s ghost listens in on conversations at his funeral.',
  'the adventurer and their noble steed swap bodies.',
  'the deities give all the people in a small village special powers and a job. they must always carry out this duty.',
  'a weapon reported to have supernatural powers has been discovered deep in the mountains.',
  'treasures beyond our comprehension are supposedly deep in a treacherous dungeon. every hero and wannabe in the realm races to find them first.',
  'a thief picks the pocket of an outsider. little does the thief know how dangerous the pilfered item truly is.',
  'a B-list hero attempts to make a name for herself by slaying the creatures that have overtaken a nearby castle.',
  'a scientist that no one likes has been tasked with learning about the language & behavior of dragons. he excels at this and thinks about taking revenge.',
  'the gnomes that helped you pass through perilous territory have come to collect on your end of the bargain.',
  'you go to bed and wake up on a tall mountain.',
  'you go to bed and wake up in the middle of a forest.',
  'you go to bed and wake up in a ship on a large sea.',
  'you go to bed and wake up inside of the castle dungeon.',
  'you go to bed and wake up at a camp with several battle hardened adventurers.',
  'you go to bed and wake up in the desert with a travelling caravan.',
  'a veteran adventurer wishes upon a shooting star - what is the wish? does it come true? does it backfire?',
];

const special = [
  'incorporate field recordings into each song',
  'use acoustic guitar as main instrument',
  'use acoustic piano as main instrument',
  'use acoustic harp as main instrument',
  'use only four instruments',
  'the album must have four songs',
  'the album must be completed in 14 days (instead of 28)',
  'base the album on poem or one page story (your own or someone else’s)',
  'base the album on public domain artwork & use this artwork on the album’s cover art',
  'base the album on a sculpture',
  'base the album on a famous landmark',
  'base the album on a place you’ve been to',
  'make heavy use of delay',
  'make heavy use of reverb',
  'make heavy use of pitch-shifting effects',
  'add at least a little bit of distortion to each instrument',
  'add at least a little bit of chorus to each instrument',
  'drums must be used in each song',
  'drums cannot be used in any song',
  'at least two songs must be in an odd meter (5/4, 7/8, etc)',
  'use a reversed audio effect in each song',
  'incorporate silence into at least two songs',
  'use only four notes in at least one song (ex: C, D, G, A; can use these notes in any octave)',
  'create a musical ‘theme’ or ‘motif’ that is used in at least half the songs (ex: a short melody or series of notes)',
  'base at least two songs on a loop that plays throughout those songs',
  'use instruments in unconventional ways (ex: drums for melody, clarinet for bass, synth lead for drums, etc)',
  'use a VST like synth1 or Dexed to create your own custom sound(s)',
  'at least one song must be under one minute long',
  'at least one song must be over five minutes long',
  'utilize volume & velocity to create a dynamic range of loud and quiet throughout the album',
  'incorporate spoken word into each song',
  'each song is the same length',
  'each song changes key at least one time',
  'each song changes tempo/BPM at least one time',
  'the final note of each song becomes the key signature of the next song',
  'incorporate a "round" into at least one song (the same melody is played on different instruments with a staggered start time so it overlaps)',
  'learn a new music theory trick/devise/practice and incorporate it into each song',
  'make a melody, then use it "upside down" later in the song',
  'trade a melody back and forth between two or more instruments',
  'use only instruments or patches that are waaaay outside your comfort zone',
  'improvise at least one song - no do overs!',
  'improvise at least one melody - no do overs!',
  'this is a "live album"',
  'use only one (1) instrument/patch',
  'use each patch/instrument as if it was not polyphonic - use only one note at a time',
  'do not use any reverb',
  'do not use any effects (reverb, delay, etc)',
];

export { albumTheme, special, styleAesthetic };
